import pickle
import numpy as np
from music21 import instrument, note, chord, stream
from model import create_network
import os

def generate_music(model_weights_path, num_generate=50, temperature=1.0):
    """
    Generate a piano midi file
    """
    # load the notes used to train the model
    with open('data/notes', 'rb') as filepath:
        notes = pickle.load(filepath)

    # Get all pitch names
    pitchnames = sorted(set(item for item in notes))
    n_vocab = len(set(notes))

    # Prepare input for the network to extract seed
    network_input = get_input_sequences(notes, pitchnames, n_vocab)
    
    # Recreate the model
    model = create_network(network_input, n_vocab)
    model.load_weights(model_weights_path)

    # Generate notes
    prediction_output = generate_notes(model, network_input, pitchnames, n_vocab, num_generate, temperature)
    
    # Create MIDI
    return create_midi(prediction_output)

def get_input_sequences(notes, pitchnames, n_vocab):
    """
    Fast sequence extraction for seed generation
    """
    note_to_int = dict((note, number) for number, note in enumerate(pitchnames))
    sequence_length = 100
    network_input = []
    
    # Fast step of 50 to avoid creating thousands of useless sequences
    for i in range(0, len(notes) - sequence_length, 50): 
        sequence_in = notes[i:i + sequence_length]
        network_input.append([note_to_int[char] for char in sequence_in])

    n_patterns = len(network_input)
    network_input = np.reshape(network_input, (n_patterns, sequence_length, 1))
    network_input = network_input / float(n_vocab)

    return network_input

def generate_notes(model, network_input, pitchnames, n_vocab, num_generate, temperature):
    """
    Generate notes from the neural network based on a sequence of notes
    """
    # pick a random sequence from the input as a starting point for the generation
    start = np.random.randint(0, len(network_input)-1)
    
    int_to_note = dict((number, note) for number, note in enumerate(pitchnames))

    pattern = network_input[start]
    # Denormalize to get the integer indices
    pattern = (pattern * n_vocab).astype(int).tolist()
    pattern = [p[0] for p in pattern] # flatten
    
    prediction_output = []

    print(f"Generating {num_generate} notes...")

    for note_index in range(num_generate):
        prediction_input = np.reshape(pattern, (1, len(pattern), 1))
        prediction_input = prediction_input / float(n_vocab)

        prediction = model.predict(prediction_input, verbose=0)
        
        # Apply temperature
        prediction = np.log(prediction[0] + 1e-7) / temperature
        exp_preds = np.exp(prediction)
        prediction = exp_preds / np.sum(exp_preds)
        
        # Sample index
        index = np.random.choice(len(prediction), p=prediction)
        
        result = int_to_note[index]
        prediction_output.append(result)

        pattern.append(index)
        pattern = pattern[1:len(pattern)]

    return prediction_output


def create_midi(prediction_output, output_file='output.mid'):
    """
    convert the output from the prediction to notes and create a midi file
    from the notes
    """
    offset = 0
    output_notes = []

    # create note and chord objects based on the values generated by the model
    for pattern in prediction_output:
        # pattern is a chord
        if ('.' in pattern) or pattern.isdigit():
            notes_in_chord = pattern.split('.')
            notes = []
            for current_note in notes_in_chord:
                new_note = note.Note(int(current_note))
                new_note.storedInstrument = instrument.Piano()
                notes.append(new_note)
            new_chord = chord.Chord(notes)
            new_chord.offset = offset
            output_notes.append(new_chord)
        # pattern is a note
        else:
            new_note = note.Note(pattern)
            new_note.offset = offset
            new_note.storedInstrument = instrument.Piano()
            output_notes.append(new_note)

        # increase offset each iteration so that notes do not stack
        # (you could make this variable in a more advanced model)
        offset += 0.5

    midi_stream = stream.Stream(output_notes)
    
    os.makedirs('outputs', exist_ok=True)
    out_path = os.path.join('outputs', output_file)
    midi_stream.write('midi', fp=out_path)
    print(f"Saved generated MIDI to {out_path}")
    return out_path
